@startuml

skinparam linetype ortho

abstract class AbstractMembre {
- string nom
- string adresse
- Date dateAdhesion
- string codeCarteAdhesion
}

class MembreParticulier {
- Date dateDeNaissance
- string numCarteIdentite
}

class MembreEntreprise {
- string numEntreprise
- string numRegistre
}

class RegistreEmploye{
  + void AjouterEmploye(infos, PointDeVente)
  + void ModifierEmploye(Employe, infos)
  + void SupprimerEmploye(Employe)
  + Employe GetEmployeById(idEmploye)
}

interface IVisitable {
+void accept(IVisitor)
}

interface IVisitor {
    +visitTransaction(Transaction)
    +visitPointDeVente(PointDeVente)
}

IVisitor -> PointDeVente
IVisitor -> Transaction
class ReportVisitor implements IVisitor {
    -int pointDeVenteCount
    -int transactionCount
}


class Employe {
- string nomComplet
- Date debutEmploi
}

class SousDirecteur {

}

class Directeur {

}

class Transaction implements IVisitable {
- int id
- AbstractMembre acheteur
- Date date
- Number prixTotal
- List<ISubscriber> subscribers
- List<Article> articles
+ Number getPrixTotal()
+ AbstractMembre getAcheteur()
+ void AjouterArticle(Article)
+ void ModifierArticle(Article, infos)
+ void SupprimerArticle(Article)
+ void ProcederPaiement()
+ void AjouterSubscriber(ISubscriber)
+ void EnleverSubscriber(ISubscriber)
+ void NotifierSubscribers()
}

class Article {
  - string SKU
  - string description
  - Number prix
  - string taille
  - Map<PointDeVente,int> quantiteLocalisation
}

class RegistreTransaction {
- List<Transaction> transactions
+ Transaction getTransactionById(idTransaction)
+ void NouvelleTransaction(AbstractMembre)
+ void AnnulerTransaction(Transaction)
+ void SupprimerTransaction(Transaction)
+ void ArchiverJournee()
}

enum StatutTransaction{
PAYE
ATTENTE_PAIEMENT
}

class Entreprise {
- string nom
- string numEntreprise
- string numRegistre
- List<AbstractMembre> membres
- List<PointDeVente> pointDeVentes
+ AbstractMembre getMembreById(idMembre)
+ void AjouterNouveauMembre(infos)
+ void ModifierMembre(AbstractMembre, infos)
+ void SupprimerMembre(AbstractMembre)
+ void ActiverMembre(AbstractMembre)
+ void DesactiverMembre(AbstractMembre)
+ void AjouterPointDeVente(SousDirecteur)
+ void ModifierPointDeVente(PointDeVente, infos)
+ void SupprimerPointDeVente()

}

class PointDeVente implements IVisitable{
  - string id
  - string adresse
  + void ChangerSousDirecteur(SousDirecteur)
  + double GetTaxes()
  + boolean VerifierCarteMembre(codeCarteAdhesion)
  + void FaireRemboursement(idTransaction)
}

interface InventaireAdapter {
  +Article GetArticleBySKU(string)
  +ReduireInventaire(Article,Quantite,PointDeVente)
}


class Inventaire

interface ISubscriber {
+ update(Transaction)
}

class RecuListener implements ISubscriber {
    - void GenererRecu(Transaction)
}

class ArchivageListener implements ISubscriber {
    - void ArchiverTransaction(Transaction)
}

Inventaire ..|> InventaireAdapter

abstract class Paiement {}

class PaiementCredit {}

class PaiementCash {}

class PaiementCheque {}

Employe <|-- SousDirecteur
SousDirecteur <|-- Directeur

Paiement <|-- PaiementCredit
Paiement <|-- PaiementCash
Paiement <|-- PaiementCheque

Entreprise *-- PointDeVente
PointDeVente *-- RegistreEmploye
Entreprise *-- InventaireAdapter
InventaireAdapter --> Article
Entreprise *-- Directeur
PointDeVente *-- SousDirecteur
RegistreEmploye *-- Employe
PointDeVente *-- RegistreTransaction

RegistreTransaction *-- Transaction
Transaction <-- StatutTransaction
Transaction *-- Paiement
Transaction o- Article

AbstractMembre --* Entreprise
MembreParticulier<|-- AbstractMembre
MembreEntreprise <|-- AbstractMembre

Transaction o- ISubscriber


@enduml