skinparam linetype ortho

abstract class AbstractMembre {
- string nom
- string adresse
- Date dateAdhésion
- string codeCarteAdhésion
}

class MembreParticulier {
- Date dateDeNaissance
- string numCarteIdentite
}

class MembreEntreprise {
- string numEntreprise
- string numRegistre
}

class RegistreEmploye{
  + void AjouterEmployé(infos, PointDeVente)
  + void ModifierEmployé(Employé, infos)
  + void SupprimerEmployé(Employé)
  + Employé getEmployéById(idEmployé)
}

interface IVisitable {
+void accept(IVisitor)
}

interface IVisitor {
    +visitTransaction(Transaction)
    +visitPointDeVente(PointDeVente)
}

IVisitor -> PointDeVente
IVisitor -> Transaction
class ReportVisitor implements IVisitor {
    -int pointDeVenteCount
    -int transactionCount
}


class Employé {
- string nomComplet
- Date debutEmploi
}

class SousDirecteur {

}

class Directeur {

}

class Transaction implements IVisitable , Iobservable {
- int id
- AbstractMembre acheteur
- Date date
- Number prixTotal
+ Number getPrixTotal()
+ AbstractMembre getAcheteur()
+ void AjouterArticle(Article)
+ void ModifierArticle(Article, infos)
+ void SupprimerArticle(Article)
+ void ProcéderPaiement()
+add observateur (observateur)
+remove observateur (observateur)
+notify()
}

class Article {
  - string SKU
  - string description
  - Number prix
  - string taille
  - Map<PointDeVente,int> quantiteLocalisation
}

class RegistreTransaction implements Iobservator {
- List<Transaction> transactions
+ Transaction getTransactionById(idTransaction)
+ void NouvelleTransaction(AbstractMembre)
+ void AnnulerTransaction(Transaction)
+ void SupprimerTransaction(Transaction)
+ void ArchiverTransaction(Transaction)
+ void ArchiverJournée()
+ void GénérerReçu(Transaction)
+action(object Sender)
}

enum StatutTransaction{
PAYÉ
ATTENTE_PAIEMENT
}

class Entreprise {
- string nom
- string numEntreprise
- string numRegistre
- List<AbstractMembre> membres
- List<PointDeVente> pointDeVentes
+ AbstractMembre getMembreById(idMembre)
+ void AjouterNouveauMembre(infos)
+ void ModifierMembre(AbstractMembre, infos)
+ void SupprimerMembre(AbstractMembre)
+ void ActiverMembre(AbstractMembre)
+ void DésactiverMembre(AbstractMembre)
+ void AjouterPointDeVente(SousDirecteur)
+ void ModifierPointDeVente(PointDeVente, infos)
+ void SupprimerPointDeVente()

}

class PointDeVente implements IVisitable{
  - string id
  - string adresse
  + void ChangerSousDirecteur(SousDirecteur)
  + double getTaxes()
  + boolean vérifierCarteMembre(codeCarteAdhésion)
  + void faireRemboursement(idTransaction)
}

interface InventaireAdapter {
  +Article GetArticleBySKU(string)
  +ReduireInventaire(Article,Quantite,PointDeVente)
}


class Inventaire

interface Iobservable {
+add observateur (observateur)
+remove observateur (observateur)
+notify(eventType, Data)
}

interface Iobservator {
+procederPaiement()
+action(object Sender) 
}


Inventaire ..|> InventaireAdapter

abstract class Paiement {}

class PaiementCredit {}

class PaiementCash {}

class PaiementCheque {}

Employé <|-- SousDirecteur
SousDirecteur <|-- Directeur

Paiement <|-- PaiementCredit
Paiement <|-- PaiementCash
Paiement <|-- PaiementCheque

Entreprise *-- PointDeVente
PointDeVente *-- RegistreEmploye
Entreprise *--- InventaireAdapter
InventaireAdapter --> Article
Entreprise *-- Directeur
PointDeVente *-- SousDirecteur
RegistreEmploye *-- Employé
PointDeVente *-- RegistreTransaction

RegistreTransaction *-- Transaction
Transaction <-- StatutTransaction
Transaction *-- Paiement
Transaction o- Article

AbstractMembre --* Entreprise
MembreParticulier<|-- AbstractMembre
MembreEntreprise <|-- AbstractMembre
